lib/cn_web/router.ex
defmodule CnWeb.Router do
  use CnWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", CnWeb do
    pipe_through :browser


    get "/", PageController, :index
    get "/new", PageController, :new
   # post "/create", PageController, :create
    get "/users/:id", UserController, :show
    post "/users", UserController, :create
    get "/user/:id/:friend", UserController, :friend
    get "/people/new", PeopleController, :new
    post "/create", PeopleController, :create
  end

  # Other scopes may use custom stacks.
  # scope "/api", CnWeb do
  #   pipe_through :api
  # end
end

lib/cn/application.ex
defmodule Cn.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    # List all child processes to be supervised
    children = [
      # Start the Ecto repository
      Cn.Repo,
      # Start the endpoint when the application starts
      CnWeb.Endpoint
      # Starts a worker by calling: Cn.Worker.start_link(arg)
      # {Cn.Worker, arg},
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Cn.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    CnWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/cn/repo.ex
defmodule Cn.Repo do
  use Ecto.Repo,
    otp_app: :cn,
    adapter: Ecto.Adapters.Postgres
end

lib/cn/social/community.ex
defmodule Cn.Social.Community do
  use Ecto.Schema
  import Ecto.Changeset

  alias Cn.Social.Community

  schema "community" do

    field :name , :string
    timestamps()
  end
  def changeset(%Community{}=community, attrs) do
    community
    |>cast(attrs,[:name])
    |>validate_required([:name])
  end


end

lib/cn/social/friend.ex
defmodule Cn.Social.Friend do
  use Ecto.Schema
  import Ecto.Changeset

  alias Cn.Social.Friend

  schema "friend" do

      field :name, :string
      field :surname, :string


      timestamps()
  end

  def changeset(%Friend{}=friend, attrs)do
    friend
    |>cast(attrs,[:name,:surname])
    |>validate_required([:name,:surname])
  end


end

lib/cn/social/login.ex
defmodule Cn.Social.Login do
  use Ecto.Schema
  import Ecto.Changeset

  alias Cn.Social.Login

  schema("login") do
    field :nickname, :string
    field :name, :string
    field :passwordhash, :string
    field :email, :string

    field :password, :string, virtual: true
    field :password_confirmation, :string, virtual: true

    timestamps()
  end

  def changeset(%Login{}=login, attrs) do
    login
    |>cast(attrs,[:nickname, :name, :email, :password, :password_confirmation])
    |>validate_confirmation(:password, message: "does not match password!")
    |>encrypt_password()
    |>validate_required([:nickname, :name, :email, :passwrodhash])
  end

  def encrypt_password(changeset)do
    with password when not is_nil(password) <- get_change(changeset, :password) do
      put_change(changeset, :passwordhash, Comeonin.Bcrypt.hashpwsalt(password))
      else
      _ -> changeset
    end

  end
end

lib/cn/social/message.ex
defmodule Cn.Social.Message do
  use Ecto.Schema
  import Ecto.Changeset

  alias Cn.Social.Message

  schema "message" do
    field :letter, :string

    timestamps()
  end

  def changeset(%Message{}=message, attrs) do
    message
    |>cast(attrs,[:letter])
    |>validate_required([:letter])
  end

end

lib/cn/social/people.ex
defmodule Cn.Social.People do
  use Ecto.Schema
  import Ecto.Changeset

  alias Cn.Social.People

  schema("peoples")do
    field :name, :string
    field :surname, :string
    field :sex, :boolean
    field :country, :string
    field :about, :string
    field :city, :string

    timestamps()
  end

  def changeset(%People{}=people, attrs)do
    people
    |>cast(attrs, [:name,:surname,:sex,:country, :about, :city])
    |>validate_required([:name,:surname,:sex,:country, :about, :city])
  end

end

lib/cn/social/social.ex
defmodule Cn.Social do
  import Ecto.Query, warn: false
  alias Cn.Repo
  alias Cn.Social.Friend
  alias Cn.Social.Community
  alias Cn.Social.Login
  alias Cn.Social.Message
  alias Cn.Social.People
  alias Cn.Social

  def list_of_frieds()do
    #Здесь будет представлен список друзей
  end
  def new_people() do
		People.changeset(%People{},{})
	end

  def new_login() do
		Login.changeset(%Login{},{})
	end

  #параметры для загрузки формы в бд
	def create_people_in_base(people_params) do
		Repo.transaction(fn ->
		with {:ok, people}<-create_people(people_params) do
				people
			else
				_ -> Repo.rollback("Failed to create poll")
		  end
	     	end)
	end

  def create_login_in_base(user_param) do
		Repo.transaction(fn ->
			with {:ok, user}<- create_login(user_param) do
				user
			else
				_ -> Repo.rollback("Failed to create user")
		end
		end)
	end

  def create_people(attrs) do
		%People{}
		|>People.changeset(attrs)
		|>Repo.insert()
	end


	def create_login(attrs) do
		%Login{}
		|>Login.changeset(attrs)
		|>Repo.insert()
	end

  def all_people do
		Repo.all(People)
	end
	def list_login do
		Repo.all(Login)
	end

	def get_user(id) do
		Repo.get(Login, id)
	end

	def get_user_by_username(username) do
    Repo.get_by(Login, username: username)
  end
end

lib/cn_web/controllers/page_controller.ex
defmodule CnWeb.PageController do
  use CnWeb, :controller
  alias Cn.Social


  def index(conn, _params) do
    render(conn, "index.html")
  end

  def new(conn, _params) do
    user = Social.new_login
    render( conn , "new_user.html", user: user)
  end
end

lib/cn_web/controllers/people_controller.ex
defmodule CnWeb.PeopleController do
  use CnWeb, :controller
  alias Cn.Social

 # def index(conn, _params) do
  #  render(conn, "index.html")
 # end
  def new(conn, _) do
      people = Social.new_people
      render conn, "new_people.html", people: people
  end

  def create(conn, %{"people"=> people_params}) do
      with {:ok, _people} <- Social.create_people_in_base(people_params)do
    conn
    |> put_flash(:info, "People created successfully")
    |> redirect(to: Routes.page_path(conn, :index))
      else
        _ ->
      conn
      |> put_flash(:error, "People Not Created")
      |> redirect(to: Routes.page_path(conn, :index))
     end
  end
end

lib/cn_web/controllers/user_controller.ex
defmodule CnWeb.UserController do
  use CnWeb, :controller
  alias Cn.Social

  def index(conn, _params) do
    render(conn, "index.html")
  end

  def new(conn, _params) do
    render(conn, "new.html")
  end

  def create(conn, %{"user"=> user_params}) do
    with {:ok, login} <- Social.create_login_in_base(user_params)do
			conn
			|> put_flash(:info, "Login created successfully")
			|> redirect(to: Routes.user_path(conn, :show, login))
          else
      {:error, _login} ->
			conn
			|> put_flash(:error, "Login Not Created")
			|> redirect(to: Routes.page_path(conn, :index))
		end
  end
  def show(conn, %{"id" => id} )do
       with {:ok, user} <- Social.get_user(id) do
         render(conn, "show.html", user: user)
         else
          _ ->
        conn
        |> put_flash(:error, "Login Not Found")
        |> redirect(to: Routes.page_path(conn, :index))

       end

  end
end

lib/cn_web/views/error_view.ex
defmodule CnWeb.ErrorView do
  use CnWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/cn_web/views/layout_view.ex
defmodule CnWeb.LayoutView do
  use CnWeb, :view
end

lib/cn_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Cn · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
            <li><a href="https://hexdocs.pm/phoenix/overview.html">Get Started</a></li>
          </ul>
        </nav>
        <a href="http://phoenixframework.org/" class="phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/phoenix.png") %>" alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/cn_web/templates/page/index.html.eex
<section class="row">
  <article class="column">
    <h2>Wlecomne to social Network</h2>
  </article>
</section>

lib/cn_web/templates/page/new.html.eex
<section class="row">
  <article class="column">
    <h2>New form</h2>
  </article>
</section>

lib/cn_web/templates/page/new_people.html.eex
<div class="people-form">
 <h2>New People</h2>
 <%= form_for @people, people_path(@conn, :create), fn f -> %>
   <label>
     Name:<br />
     <%= text_input f, :name %>
   </label>
   <br />
   <label>
     Surname<br />
     <%= text_input f, :surname %>
   </label>
   <label>

    Sex male true female false   <br/>
    <%= radio_button  f, :sex, checked: "checked"%>
   </label>
   <label>
    Country <br />
    <%= text_input f, :country %>
   </label> 
   <label>
    About <br/>
    <%= text_input f, :about%>
   </label>
   <label>
    City <br/>
    <%= text_input f, :city %>
   </label>
   <br />
   <%= submit "Create" %>
 <% end %>
</div>

lib/cn_web/templates/people/new_people.html.eex
<div class="people-form">
 <h2>New People</h2>
 <%= form_for @people, people_path(@conn, :create), fn f -> %>
   <label>
     Name:<br />
     <%= text_input f, :name %>
   </label>
   <br />
   <label>
     Surname<br />
     <%= text_input f, :surname %>
   </label>
   <label>

    Sex male true female false   <br/>
    <%= radio_button  f, :sex, checked: "checked"%>
   </label>
   <label>
    Country <br />
    <%= text_input f, :country %>
   </label> 
   <label>
    About <br/>
    <%= text_input f, :about%>
   </label>
   <label>
    City <br/>
    <%= text_input f, :city %>
   </label>
   <br />
   <%= submit "Create" %>
 <% end %>
</div>

lib/cn_web/templates/user/new_user.html.eex
<div class="user-form">
    <h2>New User</h2>
    <%= form_for @user, user_path(@conn, :create), fn f -> %>
        <label>
            Nickname:<br />
            <%= text_input f, :nickname %>
         </label>
        <label>
            Name:<br />
            <%= text_input f, :name %>
         </label>
         <label>
             Passwordhash:<br />
            <%= text_input f, :passwordhash %>
         </label>
         <label>
            Email:<br />
            <%= text_input f, :email %>
         </label>

         <%= submit "Create" %>


    <% end %>
</div>

lib/cn_web/templates/user/show.html.eex
<h1>test</h1>